import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from './theme';

export const AccountStyles = StyleSheet.create({
    auroraLogo: {
        marginTop: 1,
        marginLeft: 33,
        height: 175,
        width: 330,
        resizeMode: 'contain',
    },
    toggleText: {
        marginTop: 0,
        marginBottom: spacing.sm,
        color: colors.primary,
        textAlign: 'center',
        fontWeight: '500',
    },
    title: {
        fontSize: typography.h2.fontSize,
        fontWeight: '600',
        textAlign: 'left',
        marginTop: spacing.sm,
        marginLeft: spacing.md,
    },
    welcomeText: {
        fontSize: typography.h1.fontSize,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: spacing.md,
        marginTop: spacing.sm,
        marginLeft: spacing.sm,
        marginRight: spacing.sm,
        color: colors.text,
    },
    links: {
        color: '#007AFF', 
        fontSize: 16,
        marginLeft: spacing.sm,
    },
    signOut: {
        color: colors.text,
        fontWeight: '600',
        fontSize: 22,
        fontFamily: 'System',
        borderWidth: 1,
        borderColor: colors.text,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: 5,
    },
    savedArticles: {
        marginTop: spacing.md,
        marginBottom: 0,
        color: colors.primary,
        textAlign: 'center',
        fontWeight: '600',
        fontSize: 16,
        fontFamily: 'System',
    },
    cardContainer: {
        backgroundColor: colors.background,
        borderRadius: 10,
        marginHorizontal: spacing.md,
        marginTop: -5,
        marginBottom: spacing.md,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        overflow: 'hidden',
    },
    cardHeader: {
        alignItems: 'center',
        paddingVertical: spacing.lg,
        paddingTop: spacing.xl,
    },
    profileImageContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: spacing.md,
        overflow: 'hidden',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    profileName: {
        fontSize: typography.h2.fontSize,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: spacing.xs,
    },
    profileHandle: {
        fontSize: typography.body.fontSize,
        color: colors.text,
        opacity: 0.7,
        marginBottom: spacing.lg,
    },
    menuItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.md,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        
    },
    menuItemText: {
        fontSize: typography.body.fontSize + 2,
        color: colors.text,
    },
    arrow: {
        fontSize: typography.body.fontSize + 4,
        color: colors.text,
    },
}); 