import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from './theme';

export const AccountStyles = StyleSheet.create({
    divider: {
        borderBottomWidth: 1, 
        borderBottomColor: '#E0E0E0', 
        marginBottom: 20,
        marginHorizontal: -20,
    },
    toggleText: {
        marginTop: 0,
        marginBottom: spacing.sm,
        color: colors.primary,
        textAlign: 'center',
        fontWeight: '500',
    },
    title: {
        fontSize: typography.h3.fontSize,
        fontWeight: '500',
        textAlign: 'center',
        marginTop: spacing.sm,
        marginLeft: spacing.md,
        marginBottom: spacing.md,
    },
    welcomeText: {
        fontSize: typography.h2.fontSize,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: spacing.md,
        marginTop: spacing.sm,
        marginLeft: spacing.sm,
        marginRight: spacing.sm,
        color: colors.text,
    },
    links: {
        color: colors.primary, 
        fontSize: 16,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 5,
    },
    signOut: {
        fontWeight: '500',
        fontSize: typography.body.fontSize,
        fontFamily: 'System',
        borderWidth: 0,
        backgroundColor: '#F2F2F7',
        borderColor: colors.text,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: 5,
        color: colors.error,
    },
    editProfile: {
        fontWeight: '500',
        fontSize: typography.body.fontSize,
        fontFamily: 'System',
        borderWidth: 0,
        backgroundColor: '#F2F2F7',
        borderColor: colors.text,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: 5,
        color: colors.text,
    },
    profileImageContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: spacing.md,
        overflow: 'hidden',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    profileName: {
        fontSize: typography.h2.fontSize,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: spacing.xs,
    },
    profileHandle: {
        fontSize: typography.body.fontSize,
        color: colors.text,
        opacity: 0.7,
        marginBottom: spacing.lg,
    },
    arrow: {
        fontSize: typography.body.fontSize + 4,
        color: colors.text,
    },
    legal: {
        fontSize: typography.body.fontSize,
        color: '#999999',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    legalContainer: {
        paddingHorizontal: 20, 
        marginTop: 30, 
        alignItems: 'center',
    },
}); 