import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from './theme';

export const SignInStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    formContainer: {
        padding: spacing.xl,
    },
    title: {
        fontSize: typography.h1.fontSize,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: spacing.md,
        //marginBottom: spacing.sm,
    },
    input: {
        height: 40,
        borderColor: colors.border,
        borderWidth: 1,
        marginTop: spacing.sm,
        paddingLeft: spacing.sm,
        borderRadius: 8,
    },
    errorText: {
        color: colors.error,
        fontSize: typography.caption.fontSize,
        marginBottom: spacing.sm,
        marginTop: spacing.xs,
    },
    message: {
        fontSize: typography.caption.fontSize,
        textAlign: 'left',
        color: colors.text,
        opacity: 0.7,
    },
    requirements: {
        fontSize: typography.caption.fontSize,
        color: colors.text,
        opacity: 0.7,
        marginBottom: 0,
        marginTop: spacing.sm,
        textAlign: 'left',
    },
    eye: {
        position: 'absolute',
        right: 10,
        top: 16,
        height: 24,
        width: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    reset: {
        fontWeight: '500',
        fontSize: typography.body.fontSize,
        fontFamily: 'System',
        borderWidth: 0,
        backgroundColor: '#F2F2F7',
        borderColor: colors.text,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.lg,
        borderRadius: 5,
        color: colors.text,
        alignSelf: 'center',
        marginBottom: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    toggleText: {
        marginTop: 10,
        marginBottom: spacing.sm,
        color: colors.primary,
        textAlign: 'center',
        fontWeight: '500',
    },
    signInButton: {
        //backgroundColor: '#F2F2F7',
        paddingVertical: 12,
        borderRadius: 8,
        alignSelf: 'center',
        minWidth: 337,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
    },
    resetPasswordButton: {
        backgroundColor: '#F2F2F7',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        alignSelf: 'center',
        minWidth: 140,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        fontWeight: '500',
        fontSize: 16,
    },
    headerLogo: {
        height: 75,
        width: 225,
    },
    heading: {
        paddingTop: 80, 
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    subtitle: {
        fontSize: typography.h2.fontSize,
        opacity: 0.5,
        //marginTop: spacing.sm,
        textAlign: 'center',
    },
    forgot: {
        fontSize: typography.h3.fontSize,
        opacity: 0.5,
        textAlign: 'center',
        marginTop: spacing.sm,
        fontWeight: '400',
        marginBottom: spacing.sm,
    },
}); 