name: CI Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.actor == 'wrag20'
    name: Prebuild & EAS Production Builds
    runs-on: macos-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}

      # Android signing
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS:     ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD:  ${{ secrets.ANDROID_KEY_PASSWORD }}

      # Apple App Store Connect API key
      ASC_KEY_ID:      ${{ secrets.ASC_KEY_ID }}
      ASC_ISSUER_ID:   ${{ secrets.ASC_ISSUER_ID }}
      ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.2.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        run: eas login --token $EXPO_TOKEN

      - name: Prebuild native projects
        run: npx expo prebuild --clean --platform android,ios

      - name: Decode and setup Android keystore
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/keystore.jks
          mkdir -p ~/.android
          cat <<EOF > ~/.android/keystore.properties
          storeFile=$GITHUB_WORKSPACE/android/keystore.jks
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          keyPassword=$ANDROID_KEY_PASSWORD
          EOF

      - name: Decode App Store Connect API key
        run: |
          echo "$ASC_PRIVATE_KEY" | base64 --decode > AuthKey_${ASC_KEY_ID}.p8
          mkdir -p ~/.eas
          jq -n \
            --arg keyId "$ASC_KEY_ID" \
            --arg issuerId "$ASC_ISSUER_ID" \
            --arg privateKey "$(sed 's/$/\\n/' AuthKey_${ASC_KEY_ID}.p8)" \
            '{"keyId":$keyId, "issuerId":$issuerId, "key":$privateKey}' \
            > ~/.eas/appstoreconnect.json

      - name: Run Android production build (local)
        run: |
          eas build --local \
            --platform android \
            --profile production \
            --output ./android/app/build/outputs/aab/app-release.aab

      - name: Run iOS production build (local)
        run: |
          eas build --local \
            --platform ios \
            --profile production \
            --output ./ios/App/build/Archive/Products/Applications/AuroraAgent.app

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aurora-android-aab
          path: android/app/build/outputs/aab/app-release.aab

      - uses: actions/upload-artifact@v4
        with:
          name: aurora-ios-app
          path: ios/App/build/Archive/Products/Applications/AuroraAgent.app